services:
  site:
    image: nginx:1.27.2-alpine
    container_name: php-site.local
    volumes:
      # Mount source-code for development
      - ./:/app
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '${APP_PORT:-8088}:80'
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=php-site.local
  php:
    image: php:8.3-fpm-alpine
    container_name: php-site.local.fpm
    volumes:
      # Mount source-code for development
      - ./:/app:delegated
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
networks:
  default:
    name: nginx-proxy
    external: true
